# DataSource SQL Server
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=${DB_USER:sa}
quarkus.datasource.password=${DB_PASSWORD:YourStrong@Passw0rd}
quarkus.datasource.jdbc.url=jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME:tododb};encrypt=false

# Hibernate
quarkus.hibernate-orm.database.generation=update

# JWT — RSA public key from auth-app
# In production, override with: mp.jwt.verify.publickey.location=file:/path/to/publickey.pem
mp.jwt.verify.publickey=${JWT_PUBLIC_KEY:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArKpZNnOrrIi1YXKjFoVO8aC5yo/3VJyAQq3LAuVfM1JIWfC/E5ZgpCxitCY3LMeVQFa0SQB5iynXoAOERjKEhPZD+E7o4JCaaYzbOS6cELcdfbVLEiejgZ087qIgPXgyVRx4dAIs3WQzychwdsbRQjphcFaqGah1FdpdGbZzlshJwcYbPWmD8X0QctWuGgtsf+h2bavBTITQS5YqP8q7tVulK0ZDp2xiFfM5jiXNsNmKBz2E96xYzeQzDEmnflfqyxa6cGBkRkQLKpUhDHsv0v9uHq4an2EReSk/PLDeOuiCjj87FTx9Czq+Ub3imEIoFLjnzfF0rK03+8OHkyd14QIDAQAB}
mp.jwt.verify.issuer=${JWT_ISSUER:http://auth-app}

# Logging JSON (disable in test profile)
quarkus.log.console.json=true
%test.quarkus.log.console.json=false

# OpenAPI
quarkus.smallrye-openapi.info-title=Todo App API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=REST API for task management

# HTTP
quarkus.http.port=8080
